### ISSUE TITLE
Failure in fetch_device_json

### ISSUE THREAD

**Issue by KnicKnic** [Einstein42/myq-garage#28]
For liftmaster garage door.
Started on 2019/2/27

2019-03-02 23:51:06,931 INFO     ==================================STARTED==================================
2019-03-02 23:51:07,595 ERROR    Traceback (most recent call last):
2019-03-02 23:51:07,596 ERROR      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
2019-03-02 23:51:07,598 ERROR    httplib_response = conn.getresponse(buffering=True)
2019-03-02 23:51:07,599 ERROR    TypeError
2019-03-02 23:51:07,600 ERROR    :
2019-03-02 23:51:07,600 ERROR    getresponse() got an unexpected keyword argument 'buffering'
2019-03-02 23:51:07,601 ERROR
During handling of the above exception, another exception occurred:
2019-03-02 23:51:07,601 ERROR    Traceback (most recent call last):
2019-03-02 23:51:07,602 ERROR      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
2019-03-02 23:51:07,605 ERROR    body=body, headers=headers)
2019-03-02 23:51:07,605 ERROR      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
2019-03-02 23:51:07,608 ERROR    httplib_response = conn.getresponse()
2019-03-02 23:51:07,608 ERROR      File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
2019-03-02 23:51:07,613 ERROR    response.begin()
2019-03-02 23:51:07,614 ERROR      File "/usr/lib/python3.4/http/client.py", line 351, in begin
2019-03-02 23:51:07,617 ERROR    version, status, reason = self._read_status()
2019-03-02 23:51:07,617 ERROR      File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
2019-03-02 23:51:07,620 ERROR    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2019-03-02 23:51:07,620 ERROR      File "/usr/lib/python3.4/socket.py", line 371, in readinto
2019-03-02 23:51:07,623 ERROR    return self._sock.recv_into(b)
2019-03-02 23:51:07,624 ERROR      File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
2019-03-02 23:51:07,628 ERROR    return self.read(nbytes, buffer)
2019-03-02 23:51:07,628 ERROR      File "/usr/lib/python3.4/ssl.py", line 617, in read
2019-03-02 23:51:07,632 ERROR    v = self._sslobj.read(len, buffer)
2019-03-02 23:51:07,632 ERROR    ConnectionResetError
2019-03-02 23:51:07,633 ERROR    :
2019-03-02 23:51:07,634 ERROR    [Errno 104] Connection reset by peer
2019-03-02 23:51:07,634 ERROR
During handling of the above exception, another exception occurred:
2019-03-02 23:51:07,635 ERROR    Traceback (most recent call last):
2019-03-02 23:51:07,635 ERROR      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
2019-03-02 23:51:07,637 ERROR    timeout=timeout
2019-03-02 23:51:07,638 ERROR      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
2019-03-02 23:51:07,641 ERROR    _pool=self, _stacktrace=stacktrace)
2019-03-02 23:51:07,642 ERROR      File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 245, in increment
2019-03-02 23:51:07,644 ERROR    raise six.reraise(type(error), error, _stacktrace)
2019-03-02 23:51:07,644 ERROR      File "/usr/lib/python3/dist-packages/six.py", line 624, in reraise
2019-03-02 23:51:07,648 ERROR    raise value.with_traceback(tb)
2019-03-02 23:51:07,648 ERROR      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
2019-03-02 23:51:07,651 ERROR    body=body, headers=headers)
2019-03-02 23:51:07,652 ERROR      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
2019-03-02 23:51:07,654 ERROR    httplib_response = conn.getresponse()
2019-03-02 23:51:07,655 ERROR      File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
2019-03-02 23:51:07,660 ERROR    response.begin()
2019-03-02 23:51:07,660 ERROR      File "/usr/lib/python3.4/http/client.py", line 351, in begin
2019-03-02 23:51:07,663 ERROR    version, status, reason = self._read_status()
2019-03-02 23:51:07,664 ERROR      File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
2019-03-02 23:51:07,666 ERROR    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2019-03-02 23:51:07,667 ERROR      File "/usr/lib/python3.4/socket.py", line 371, in readinto
2019-03-02 23:51:07,669 ERROR    return self._sock.recv_into(b)
2019-03-02 23:51:07,670 ERROR      File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
2019-03-02 23:51:07,674 ERROR    return self.read(nbytes, buffer)
2019-03-02 23:51:07,675 ERROR      File "/usr/lib/python3.4/ssl.py", line 617, in read
2019-03-02 23:51:07,678 ERROR    v = self._sslobj.read(len, buffer)
2019-03-02 23:51:07,679 ERROR    urllib3.exceptions
2019-03-02 23:51:07,679 ERROR    .
2019-03-02 23:51:07,680 ERROR    ProtocolError
2019-03-02 23:51:07,680 ERROR    :
2019-03-02 23:51:07,681 ERROR    ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2019-03-02 23:51:07,681 ERROR
During handling of the above exception, another exception occurred:
2019-03-02 23:51:07,682 ERROR    Traceback (most recent call last):
2019-03-02 23:51:07,682 ERROR      File "myq-garage.py", line 397, in <module>
2019-03-02 23:51:07,685 ERROR    myq_main()
2019-03-02 23:51:07,686 ERROR      File "myq-garage.py", line 365, in myq_main
2019-03-02 23:51:07,688 ERROR    device_instances = myq.get_devices()
2019-03-02 23:51:07,689 ERROR      File "myq-garage.py", line 311, in get_devices
2019-03-02 23:51:07,691 ERROR    res = self.fetch_device_json()
2019-03-02 23:51:07,692 ERROR      File "myq-garage.py", line 293, in fetch_device_json
2019-03-02 23:51:07,694 ERROR    req = self.session.get(self.enumurl, headers=self.headers, params=payload)
2019-03-02 23:51:07,695 ERROR      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 469, in get
2019-03-02 23:51:07,696 ERROR    return self.request('GET', url, **kwargs)
2019-03-02 23:51:07,696 ERROR      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
2019-03-02 23:51:07,698 ERROR    resp = self.send(prep, **send_kwargs)
2019-03-02 23:51:07,698 ERROR      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
2019-03-02 23:51:07,700 ERROR    r = adapter.send(request, **kwargs)
2019-03-02 23:51:07,700 ERROR      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 407, in send
2019-03-02 23:51:07,701 ERROR    raise ConnectionError(err, request=request)
2019-03-02 23:51:07,702 ERROR    requests.exceptions
2019-03-02 23:51:07,702 ERROR    .
2019-03-02 23:51:07,702 ERROR    ConnectionError
2019-03-02 23:51:07,703 ERROR    :
2019-03-02 23:51:07,703 ERROR    ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by KnicKnic** [comment]
I am closing this due to it now working again. I don't change anything, I wonder if there was a server down somewhere.
