### ISSUE TITLE
myq-garage stopped working this week

### ISSUE THREAD

**Issue by sinkr** [Einstein42/myq-garage#29]
This is the error (it previously worked perfectly):

2019-10-27 17:57:41,132 INFO     ==================================STARTED==================================
2019-10-27 17:57:41,292 ERROR    Traceback (most recent call last):
2019-10-27 17:57:41,293 ERROR      File "/usr/lib/cgi-bin/myq-garage.py", line 407, in <module>
2019-10-27 17:57:41,293 ERROR    gdoor_main()
2019-10-27 17:57:41,293 ERROR      File "/usr/lib/cgi-bin/myq-garage.py", line 373, in gdoor_main
2019-10-27 17:57:41,293 ERROR    myq = MyQ()
2019-10-27 17:57:41,293 ERROR      File "/usr/lib/cgi-bin/myq-garage.py", line 224, in __init__
2019-10-27 17:57:41,293 ERROR    self.read_token()
2019-10-27 17:57:41,293 ERROR      File "/usr/lib/cgi-bin/myq-garage.py", line 250, in read_token
2019-10-27 17:57:41,293 ERROR    self.login()
2019-10-27 17:57:41,293 ERROR      File "/usr/lib/cgi-bin/myq-garage.py", line 270, in login
2019-10-27 17:57:41,293 ERROR    print "Login err code: " + req.status_code
2019-10-27 17:57:41,293 ERROR    TypeError
2019-10-27 17:57:41,293 ERROR    :
2019-10-27 17:57:41,293 ERROR    cannot concatenate 'str' and 'int' objects

**Comment by psmith3** [comment]
Mine too. Looks like the API has changed. Found another project that has recently been updated and using a different API url of "https://api.myqdevice.com/api/v{0}".format(API_VERSION)" and APPID for chamberlain on "JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu". I am trying to get mine to work with these settings. Not sure if @Einstein42 is updating this app anymore. 

The other Github project is at https://github.com/arraylabs/pymyq/

**Comment by brbeaird** [comment]
Yep. The MyQ V5 API has some significant changes. https://github.com/arraylabs/pymyq/issues/22#issuecomment-518861064

**Comment by psmith3** [comment]
> Yep. The MyQ V5 API has some significant changes. [arraylabs/pymyq#22 (comment)](https://github.com/arraylabs/pymyq/issues/22#issuecomment-518861064)

Are you back and running with myq-garage or implementing something new?

**Comment by brbeaird** [comment]
No, I'm running with pymyq and the SmartThings_MyQ implementations. I follow this repo and a few others just to see what other people come up with.

**Comment by psmith3** [comment]
> No, I'm running with pymyq and the SmartThings_MyQ implementations. I follow this repo and a few others just to see what other people come up with.

Thanks. I am trying to get pymyq up and running on a Synology NAS and am having a hard time just trying to figure out how to run it. I am new to asyncio and have everything installed on the Synology and have my credentials in the example file, but am striking out. Would be awesome if you have any pointers on how to get it up and running. I have an ISY994i that I have been issuing commands via Flask to run my-garage and that has worked great for a while now. Trying to figure out how to shoehorn this into it's place.

**Comment by sinkr** [comment]
Yes, I'll second a pymyq howto.  I have it running, successfully logging in, and I'm doing rudimentary prints of the myq object, but that's about as far as I've gotten.  @brbeaird do you have any pointers to give?

**Comment by sinkr** [comment]
@psmith3  are you using the git version or doing a simple pip install?  I had to go to their Github repo and get the latest code to get what I needed, but it works beautifully!

**Comment by psmith3** [comment]
> @psmith3 are you using the git version or doing a simple pip install? I had to go to their Github repo and get the latest code to get what I needed, but it works beautifully!

I have tried both and now have it installed via Pip3. I had trouble installing in the native Python 2.7  environment and did install in a Python3.5  virtual environment. I have also installed via Pip3 the aiohttp dependency. I have my chamberlain credentials loaded into the example.py file a trying running and get the following error. 
`python3 example.py 
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from aiohttp import ClientSession
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 13, in <module>
    from yarl import URL
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/yarl/__init__.py", line 11, in <module>
    from .quoting import _Quoter, _Unquoter
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/yarl/quoting.py", line 3, in <module>
    from typing import Optional, TYPE_CHECKING, cast
ImportError: cannot import name 'TYPE_CHECKING'
`

**Comment by psmith3** [comment]
@Einstein42 Are you working on updating the latest Chamberlain API changes into this project? I know just enough about Python to be dangerous and doing this myself is beyond my knowledge.  Was hoping you might have an update. I would honestly rather see a Polyglot implementation, but had my-garage already working with my ISY994i and using Flash to send the commands. I see you have had a lot of other projects going on and was wondering if this one is on your list or not. 

Thanks much for this great project.

**Comment by sinkr** [comment]
@psmith3 have you tried cloning the repo and doing a python setup.py install to see if your above-mentioned issue goes away?

**Comment by psmith3** [comment]
> @psmith3 have you tried cloning the repo and doing a python setup.py install to see if your above-mentioned issue goes away?

I have not. I am doing a pip install in via flask in docker to install. I can give that a try. So has the code been updated tot he latest API?

**Comment by sinkr** [comment]
Sorry, I thought we were talking about pymyq, not myq-garage.  pygmyq does
work, however.

**Comment by psmith3** [comment]
Oh. Ok. That makes sense. No, I have not tried cloning the repo on pymyq, but can.
